# Generated by Django 5.0.8 on 2024-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='value1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
