# Generated by Django 5.0.8 on 2024-08-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_value1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('car_ID', models.AutoField(primary_key=True, serialize=False)),
                ('car_MODELO', models.CharField(max_length=200)),
                ('car_MARCA', models.CharField(max_length=200)),
                ('car_ANO_FABRICACAO', models.IntegerField(blank=True, null=True)),
                ('car_ANO_MODELO', models.IntegerField(blank=True, null=True)),
                ('car_VALOR', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
