# Generated by Django 5.0.8 on 2024-08-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_car_marca_carro_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Car',
        ),
    ]
